spring:
  application:
    name: java-buscacep-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:45432/buscacep}
    username: ${SPRING_DATASOURCE_USERNAME:buscacep}
    password: ${SPRING_DATASOURCE_PASSWORD:buscacep}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}

cep:
  client:
    wiremock-url: ${CEP_CLIENT_WIREMOCK_URL:http://localhost:8081}
    viacep-url: ${CEP_CLIENT_VIACEP_URL:https://viacep.com.br/ws}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
